System.Console.WriteLine("Введите координаты х1");
int x1 = Convert.ToInt32(Console.ReadLine());
System.Console.WriteLine("Введите координаты y1");
int y1 = Convert.ToInt32(Console.ReadLine());
System.Console.WriteLine("Введите координаты z1");
int z1 = Convert.ToInt32(Console.ReadLine());
System.Console.WriteLine("Введите координаты х1");
int x2 = Convert.ToInt32(Console.ReadLine());
System.Console.WriteLine("Введите координаты y2");
int y2 = Convert.ToInt32(Console.ReadLine());
System.Console.WriteLine("Введите координаты z2");
int z2 = Convert.ToInt32(Console.ReadLine());
double dist = Math.Sqrt(Math.Pow((x2-x1), 2) + (Math.Pow((y2-y1), 2)) + (Math.Pow((z2-z1), 2)));
Console.WriteLine($"Расстояние между двумя точками {Math.Round(dist, 1)}");